apiVersion: stable.instaclustr.com/v1
kind: CassandraDataCenter
metadata:
  name: foo-cassandra
  labels:
    app: cassandra
    chart: cassandra-0.1.0
    release: foo
spec:
  replicas: 3
  cassandraImage: "gcr.io/cassandra-operator/cassandra:latest"
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  imagePullPolicy: Always
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  dataVolumeClaim:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
